source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXInput_Example', :exclusive => true do
  pod "BXInput", :path => "../"
end

target 'BXInput_Tests', :exclusive => true do
  pod "BXInput", :path => "../"

  
end
